### ISSUE TITLE
Bump demo with production?

### ISSUE THREAD

**Issue by corneliusroemer** [pathoplexus/loculus_deployments#39]
Now that we have dedicated staging, we can probably keep demo and production in sync - which will make our demo more demo-like.

We can just change the "promote" action to include demo, I think. @theosanderson thoughts?

**Comment by theosanderson** [comment]
Yeah I vaguely thought about this. I agree the current situation isn't great. There is also slightly increased risk from trying to bump them at the same time as it creates more load on the machines. Ideal would be an hour later or something

**Comment by corneliusroemer** [comment]
In that case let's make 2 PRs and just merge them slightly apart. We could make the demo merge not require review for example?

**Comment by theosanderson** [comment]
Sounds ok to me

**Comment by corneliusroemer** [comment]
Resolved by #44
